/**
 * Inline RSL 1.0 policy + Context License metadata.
 *
 * Edit these to match your site. The Worker:
 *   - Serves `/robots.txt` from `ROBOTS_TXT` (RSL 1.0 directives)
 *   - Serves `/.well-known/context-license.json` from `CONTEXT_LICENSE`
 *   - Applies the RSL policy to every incoming request, charging
 *     `OFFER` to bots that hit Disallowed paths
 *
 * For larger sites: move both into a KV namespace and fetch them in
 * the request handler. Uncomment the `CRAWLERTOLL_CONFIG` binding in
 * `wrangler.toml` to enable.
 */

import type { PaymentOffer } from "@crawlertoll/core";

/** The default per-crawl offer surfaced when the decision is 402. */
export const OFFER: PaymentOffer = {
  rail: "x402",
  priceMicros: 5_000, // $0.005 per crawl
  currency: "USD",
  publisher: "example",
  endpoint: "default",
};

/**
 * RSL 1.0 robots.txt. Reddit, Yahoo, People Inc., Medium, Quora,
 * O'Reilly, Stack Overflow, and Cloudflare are all signatories.
 */
export const ROBOTS_TXT = `# RSL 1.0 — Really Simple Licensing
# Generated by crawlertoll-cloudflare-template
# Edit src/policy.ts to customise.

User-agent: GPTBot
User-agent: ClaudeBot
User-agent: PerplexityBot
User-agent: CCBot
User-agent: Google-Extended
User-agent: Applebot-Extended
User-agent: Meta-ExternalAgent
User-agent: Bytespider
Disallow: /
Allow: /public
License: https://example.com/ai-license
Permits: ai-search, rag
Prohibits: ai-training, redistribution-without-attribution
Compensation: per-crawl 5000 micros USD https://example.com/pay
Standard: RSL/1.0

User-agent: *
Disallow:

Sitemap: https://example.com/sitemap.xml
`;

/**
 * Context License metadata — served at /.well-known/context-license.json.
 *
 * The buyer SDK (\`@crawlertoll/client\`) reads this to discover your
 * endpoints, pricing, payment rails, and attestation key before it
 * makes a request. Customise to match your real endpoints.
 *
 * To validate this object: \`npx @crawlertoll/parser validate ./out/.well-known/context-license.json\`.
 */
export const CONTEXT_LICENSE = {
  $schema: "https://schemas.crawlertoll.com/context-license/v1.json",
  version: "1.0.0",
  publisher: {
    name: "Example Publisher",
    slug: "example",
    domain: "example.com",
    contact: "ai@example.com",
  },
  endpoints: [
    {
      name: "default",
      url: "https://example.com/api",
      transport: "streamable-http" as const,
      description: "Default API endpoint for example.com.",
    },
  ],
  pricing: {
    model: "per_query" as const,
    currency: "USD" as const,
    unit_price_micros: 5_000,
  },
  auth: {
    schemes: ["anonymous", "api_key", "x402"] as const,
  },
  terms_of_use: "https://example.com/ai-terms",
  quality_signals: {
    uptime_sla_pct: 99.0,
    freshness_target_seconds: 86_400,
    last_updated: new Date().toISOString(),
  },
};
